-- Limpieza previa en caso de que algo haya fallado antes
DROP TABLE IF EXISTS "saleItems" CASCADE;
DROP TABLE IF EXISTS sales CASCADE;
DROP TABLE IF EXISTS "orderItems" CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS waste CASCADE;
DROP TABLE IF EXISTS "cashControl" CASCADE;
DROP TABLE IF EXISTS "barTables" CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS settings CASCADE;

-- 1. Tabla de Usuarios
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT, 
  role TEXT NOT NULL DEFAULT 'cashier',
  name TEXT NOT NULL
);

-- 2. Tabla de Productos
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  "priceBottle" NUMERIC NOT NULL,
  "priceShot" NUMERIC,
  stock INT NOT NULL DEFAULT 0,
  "stockMin" INT NOT NULL DEFAULT 0,
  "shotsPerBottle" INT,
  "trackShots" BOOLEAN DEFAULT false,
  image TEXT
);

-- 3. Tabla de Mesas (Bar Tables)
CREATE TABLE "barTables" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number TEXT NOT NULL UNIQUE,
  capacity INT NOT NULL,
  status TEXT NOT NULL DEFAULT 'available',
  "currentOrderId" BIGINT
);

-- 4. Tabla de Pedidos (Orders)
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tableId" BIGINT REFERENCES "barTables"(id),
  status TEXT NOT NULL DEFAULT 'pending',
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  total NUMERIC NOT NULL DEFAULT 0,
  items JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- 5. Tabla de Items de Pedidos (Order Items) - Opcional, pero lo dejamos por si quieres escalar
CREATE TABLE "orderItems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  "productId" BIGINT REFERENCES products(id),
  "productName" TEXT NOT NULL,
  type TEXT NOT NULL,
  price NUMERIC NOT NULL,
  quantity INT NOT NULL
);

-- 6. Tabla de Ventas Consolidadas (Sales)
CREATE TABLE sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "userId" BIGINT REFERENCES users(id),
  "userName" TEXT NOT NULL,
  total NUMERIC NOT NULL,
  discount NUMERIC NOT NULL DEFAULT 0,
  "paymentMethod" TEXT NOT NULL,
  "splitCount" INT NOT NULL DEFAULT 1,
  items JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- 7. Tabla de Detalles de Ventas (Sale Items) - Opcional
CREATE TABLE "saleItems" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "saleId" BIGINT REFERENCES sales(id) ON DELETE CASCADE,
  "productId" BIGINT REFERENCES products(id),
  "productName" TEXT NOT NULL,
  type TEXT NOT NULL,
  price NUMERIC NOT NULL,
  quantity INT NOT NULL
);

-- 8. Tabla de Control de Caja (Cash Control)
CREATE TABLE "cashControl" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "userId" BIGINT REFERENCES users(id),
  amount NUMERIC NOT NULL,
  notes TEXT
);

-- 9. Tabla de Desperdicios/Mermas (Waste)
CREATE TABLE waste (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" BIGINT REFERENCES products(id),
  "productName" TEXT NOT NULL,
  quantity INT NOT NULL,
  reason TEXT NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. (Opcional) Tabla de Configuraciones
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL
);

-- ==========================================
-- Insertar datos iniciales (Semillas)
-- ==========================================

INSERT INTO users (username, password, role, name) VALUES
('admin', '123', 'admin', 'Administrador'),
('caja1', '123', 'cashier', 'Cajero Principal')
ON CONFLICT DO NOTHING;

INSERT INTO products (name, category, "priceBottle", "priceShot", stock, "stockMin", "shotsPerBottle", "trackShots") VALUES
('Aguardiente Antioqueño', 'Licores', 120000, 8000, 24, 5, 29, true),
('Ron Viejo de Caldas', 'Licores', 110000, 7500, 18, 4, 28, true),
('Cerveza Club Colombia', 'Cervezas', 8000, NULL, 120, 24, NULL, false),
('Cerveza Corona', 'Cervezas', 12000, NULL, 72, 12, NULL, false),
('Margarita Classic', 'Cocteles', 25000, NULL, 100, 0, NULL, false),
('Coca Cola 400ml', 'Bebidas sin alcohol', 6000, NULL, 48, 10, NULL, false),
('Nachos con Queso', 'Snacks', 18000, NULL, 30, 5, NULL, false)
ON CONFLICT DO NOTHING;

INSERT INTO "barTables" (number, capacity, status) VALUES
('1', 4, 'available'),
('2', 4, 'available'),
('3', 2, 'available'),
('4', 6, 'available'),
('5', 4, 'available'),
('6', 2, 'available'),
('VIP 1', 10, 'available'),
('Barra 1', 1, 'available'),
('Barra 2', 1, 'available')
ON CONFLICT DO NOTHING;
